---
- hosts: compute 
  remote_user: root
  tasks:
    - name: OpenHPC
      yum: name=http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm

    - name: Yum Update
      yum: name=*,epel-release state=latest

    - name: Yum Packages
      yum:
        name:
          - git
          - ohpc-base
          - nmap 
          - gcc
          - vim
          - emacs
          - nano
          - git
          - autogen
          - autoconf-ohpc
          - automake-ohpc
          - gzip
          - tar
          - unzip
          - stress
          - tmux
          - zsh
          - wget
          - curl
          - cmake
          - rsync
          - ufw
          - ntp
        state: latest

    - name: Clone Git Repo
      git:
        repo: https://github.com/agundimeda/factotum
        dest: /root/factotum
        force: yes

    - name: firewalld add ntp rule
      firewalld:
        service: ntp
        permanent: true
        state: enabled

    - name: Upload ntp.conf
      copy:
        src: /root/factotum/files/ntp.conf
        dest: /etc/ntp.conf

    - name: Enable service ntpd
      service:
        name: ntpd
        enabled: yes

    - name: start ntpd
      service:
        name: ntpd
        state: started

    - name: Upload Hosts file
      copy:
        src: /root/factotum/files/etchosts
        dest: /etc/hosts

    - name: Upload ssh knownhosts
      copy:
        src: /root/factotum/files/sshknownhosts
        dest: /root/.ssh/known_hosts

    - name: Upload ssh authorized_keys
      copy:
        src: /root/factotum/files/sshauthorizedkeys
        dest: /root/.ssh/authorized_keys

    - name: Upload ssh private key
      copy:
        src: /root/factotum/files/sshprivatekey
        dest: /root/.ssh/id_rsa
        mode: 0400


