---
- hosts: compute
  remote_user: root
  tasks:

    - name: Install Slurm
      yum: 
        name:
          - munge-ohpc
          - munge-libs-ohpc
          - munge-devel-ohpc 
          - ohpc-slurm-client
        state: latest

    - name: Upload Munge key
      copy:
        src: /etc/munge/munge.key
        dest: /etc/munge/

    - name: Permissions Munge
      shell: sh /root/factotum/scripts/mungeCompute.sh 

    - name: Upload Slurm Config
      copy:
        src: /root/factotum/files/slurm/slurm.conf
        dest: /etc/slurm/
    
    - name: Upload Cgroup Config
      copy:
        src: /root/factotum/files/slurm/cgroup.conf
        dest: /etc/slurm/

    - name: Permissions & Files
      shell: sh /root/factotum/scripts/slurmCompute.sh


    - name: Enable service munge
      service:
         name: munge
         enabled: yes

    - name: Start service munge
      service:
         name: munge
         state: started

    - name: Enable service slurmd
      service:
         name: slurmd
         enabled: yes

    - name: Start service slurmd
      service:
         name: slurmd
         state: started
