---
- hosts: head
  remote_user: root
  tasks:
    - name: Create Users & Groups
      shell: sh /root/factotum/files/users.sh
    
    - name: Install Slurm & Munge
      yum: 
        name: 
          - munge-ohpc
          - munge-libs-ohpc
          - munge-devel-ohpc
          - ohpc-slurm-server
        state: latest

    - name: Create Munge Key
      shell: sh /root/factotum/files/mungeHead.sh

    - name: Upload Slurm Config
      copy:
        src: /root/factotum/files/slurm.conf
        dest: /etc/slurm/

    - name: Upload GRES Config
      copy:
        src: /root/factotum/files/gres.conf
        dest: /etc/slurm/
    
    - name: Upload CGROUP Config
      copy:
        src: /root/factotum/files/cgroup.conf
        dest: /etc/slurm/

    - name: Permissions & Files
      shell: sh /root/factotum/files/slurmHead.sh
