- hosts: head
  remote_user: root
  tasks:
    - name: Software Collections
      yum: name=centos-release-scl

    - name: OOD Repository
      yum: name=https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm

    - name: OOD Package
      yum: name=ondemand
