---
- hosts: head
  remote_user: root
  tasks:
    - name: OpenHPC
      yum: name=http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm

    - name: Yum Update
      yum: name=*,epel-release,ohpc-base state=latest
    
    - name: Yum Packages
      yum:
        name:
          - nmap 
          - gcc
          - vim
          - emacs
          - nano
          - autogen
          - autoconf-ohpc
          - automake-ohpc
          - gzip
          - tar
          - unzip
          - stress
          - python34
          - python2-pip
          - python34-pip
          - octave
          - R
          - svn
          - tmux
          - zsh
          - wget
          - curl
          - anaconda-core
          - singularity-ohpc
          - mpich
          - cmake
          - gcc-gfortran
          - maven
          - openldap-clients
          - nss-pam-ldapd
          - rsync
          - oddjob-mkhomedir
          - munge-ohpc
          - munge-libs-ohpc
          - munge-devel-ohpc
          - rng-tools
        state: latest
