---
- hosts: head
  remote_user: root
  tasks:
    - name: OpenHPC
      yum:name=http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm

    - name: Update
      yum: name=*,epel-release state=latest

    - name: Packages
      yum: name={{item}} state=latest
      with_items:
        - ohpc-base
        - nmap 
        - gcc
        - vim
        - g++
        - emacs
        - nano
        - git
        - autogen
        - autoconf
        - automake
        - bzip
        - gzip
        - tar
        - unzip
        - environment-modules
        - stress
        - python
        - python3
        - R
        - octave
        - svn
        - tmux
        - zsh
        - wget
        - curl
        - miniconda
        - singularity-ohpc
        - mpich
        - cmake
        - gcc-gfortran
        - ipmitool
        - maven
        - openldap-clients
        - nss-pam-ldapd
        - rsync
        - mariadb-server
        - mariadb-devel
        - yum-utils
        - oddjob-mkhomedir